# Generated by Django 5.2.5 on 2025-12-01 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motorista', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
