# Generated by Django 5.2.5 on 2025-12-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_motorista_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='status',
            field=models.CharField(choices=[('NÃO_INICIADA', 'Não Iniciada'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADA', 'Finalizada')], default='NÃO_INICIADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='data_hora_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='data_hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='hodometro_chegada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='hodometro_saida',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
